//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotosStore.WebUI.ManufacturersService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManufacturersService.IManufacturers")]
    public interface IManufacturers {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturers/DoWork", ReplyAction="http://tempuri.org/IManufacturers/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturers/DoWork", ReplyAction="http://tempuri.org/IManufacturers/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturers/ReturnBrands", ReplyAction="http://tempuri.org/IManufacturers/ReturnBrandsResponse")]
        System.Data.DataSet ReturnBrands();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManufacturers/ReturnBrands", ReplyAction="http://tempuri.org/IManufacturers/ReturnBrandsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnBrandsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManufacturersChannel : PhotosStore.WebUI.ManufacturersService.IManufacturers, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManufacturersClient : System.ServiceModel.ClientBase<PhotosStore.WebUI.ManufacturersService.IManufacturers>, PhotosStore.WebUI.ManufacturersService.IManufacturers {
        
        public ManufacturersClient() {
        }
        
        public ManufacturersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManufacturersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Data.DataSet ReturnBrands() {
            return base.Channel.ReturnBrands();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnBrandsAsync() {
            return base.Channel.ReturnBrandsAsync();
        }
    }
}
